language: cpp

compiler:
  - gcc

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.8
            - gcc-4.8
            - libstdc++-4.8-dev
            - binutils
      env:
         - MATRIX_EVAL="CC=gcc-4.8 && CXX=g++-4.8"

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - sudo apt-get install libgl1-mesa-dev
  - sudo apt-get install libx11-dev
  - sudo apt-get install libxrandr-dev
  - sudo apt-get install libfreetype6-dev
  - sudo apt-get install libglew1.5-dev
  - sudo apt-get install libjpeg8-dev
  - sudo apt-get install libsndfile1-dev
  - sudo apt-get install libopenal-dev
  - sudo apt-get install libudev-dev
  - cd SFML-2.4.2/ && cmake . && make && cd ..
  - cp SFML-2.4.2/lib/*.* SFML/SFML-2.4.2-Linux64/lib/
  - make -C flappybird/