language: cpp

compiler:
  - gcc

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.8
            - gcc-4.8
            - libstdc++-4.8-dev
            - binutils
      env:
         - MATRIX_EVAL="CC=gcc-4.8 && CXX=g++-4.8"

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - tar zxvf binutils-2.22.tar.gz
  - cd binutils-2.22
  - ./configure --with-sysroot
  - make
  - sudo make install
  - cd ..
  - cd SFML-2.4.2/ && cmake . && make
  - cp SFML-2.4.2/lib/*.* SFML/SFML-2.4.2-Linux64/lib/
  - make -C flappybird/