language: c
before_install:
    - sudo apt-get install python-software-properties
    - sudo apt-get update -qq
    - sudo apt-get install -qq g++-4.8
    - export CXX="g++-4.8" CC="gcc-4.8"

script:
- make -C flappybird/